### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [promcon/website#245]
This is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to:
  - A suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), 
  which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks (stages 1, 2 & 3):

- [x] From the Prometheus websites data stream (`G-80ZM8LGB96`), configure cross-domain measurement to [promcon.io].
- [x] Configure GA4 website ID ([gtag.js]) through [Netlify snippet injection]
- [x] Confirm that the GA4 site tag is receiving events
- [x] Confirm that the UA site tag, `UA-58468480-3`, is still receiving events

### Notes

- Related: https://github.com/prometheus/docs/issues/2181
- For later: #246
- Note: the UA tag can't be connected from the GA4 tag because it isn't using the [gtag.js] library, but even if it was, we'd want to avoid sending main-site events to the promcon UA tag and so it is easier to avoid connecting them than to setup filters (that would be useful only for a short period anyways, until UA is dropped by Google).

/cc @nate-double-u @caniszczyk @juliusv 

---

Current website analytics info:

- UA site tag: `UA-58468480-3`

Hugo layout relevant for the main tag:

- https://github.com/promcon/website/blob/0cf826e966e0b3f2320f31288df17fef698fae8a/layouts/default.html#L58-L67

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[promcon.io]: https://promcon.io
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
@juliusv - I've setup GA4 via [Netlify snippet injection](https://docs.netlify.com/site-deploys/post-processing/snippet-injection/), while keeping the UA site tag as it is currently -- so no code changes were necessary.

All that will be left to do later is to drop the UA-specific code from the website (#246), once you've decided that you don't want to use that property anymore, or it stops receiving data (in 2023).

Closing the issue since all is done for now.

**Comment by juliusv** [comment]
Great, thanks!
